# @format

services:
  app:
    image: analytics-api:v1
    build:
      context: .
      dockerfile: Dockerfile.web
    # environment:
    #   - PORT=8002
    #   - DATABASE_URL=postgresql+psycopg://time-user:time-pw@db_service:5432/timescaledb
    env_file:
      - .env.compose
    ports:
      - "8080:8002"
    command: uvicorn main:app --host 0.0.0.0 --port 8002 --reload
    volumes:
      - ./src:/code:rw
    develop:
      watch:
        - action: rebuild
          path: Dockerfile
        - action: rebuild
          path: requirements.txt
        - action: rebuild
          path: compose.yaml
  db_services:
    image: timescale/timescaledb:latest-pg17
    environment:
      POSTGRES_USER: time-user
      POSTGRES_PASSWORD: time-pw
      POSTGRES_DB: timescaledb
    volumes:
      - timescalbedb_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - "5432"

volumes:
  timescalbedb_data:
